tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sachaos/todoist"
tap "sass/sass"
brew "bat"
brew "curl"
brew "composer"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "lazydocker"
brew "lazygit"
brew "lf"
brew "lua"
brew "markdownlint-cli"
brew "mas"
brew "ncdu"
brew "neovim"
brew "nvm"
brew "php@7.4", link: true
brew "rclone"
brew "ripgrep"
brew "rsync"
brew "stylua"
brew "tmux"
brew "tree"
brew "wget"
cask "android-file-transfer"
cask "appdelete"
cask "authy"
cask "brave-browser"
cask "caffeine"
cask "docker"
cask "figma"
cask "fluid"
cask "font-hasklug-nerd-font"
cask "free-ruler"
cask "gimp"
cask "google-chrome-canary"
cask "imagealpha"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "keybase"
cask "knockknock"
cask "krisp"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-json"
cask "send-to-kindle"
cask "simplenote"
cask "spotify"
cask "the-unarchiver"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
mas "BetterSnapTool", id: 417375580
mas "Bitwarden", id: 1352778147
mas "Fantastical", id: 975937182
mas "Harvest", id: 506189836
mas "NexiGo Webcam Settings", id: 1568831522
mas "Sip", id: 507257563
mas "Slack", id: 803453959
mas "Todoist", id: 585829637
mas "VOX", id: 461369673
